# Generated by Django 2.2 on 2019-04-15 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_khtmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='khrainfall',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khtmax',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khtmin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='khrainfall',
            unique_together={('date', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='khtmax',
            unique_together={('date', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='khtmin',
            unique_together={('date', 'country')},
        ),
        migrations.RemoveField(
            model_name='khrainfall',
            name='month',
        ),
        migrations.RemoveField(
            model_name='khrainfall',
            name='year',
        ),
        migrations.RemoveField(
            model_name='khtmax',
            name='month',
        ),
        migrations.RemoveField(
            model_name='khtmax',
            name='year',
        ),
        migrations.RemoveField(
            model_name='khtmin',
            name='month',
        ),
        migrations.RemoveField(
            model_name='khtmin',
            name='year',
        ),
    ]
